### ISSUE TITLE
When a chunk is appended to an existing chunk on ADLS a new line break is missing

### ISSUE THREAD

**Issue by shibug** [oleewere/fluent-plugin-azurestorage-gen2#4]
Using the latest version 0.14, when a chunk is appended to an existing chunk on ADLS a new line break is missing between the last record from the previous chunk and the first record from the latest chunk.  My configuration is as below:

> @type azurestorage_gen2
      @log_level debug
      azure_storage_account        storage
      azure_instance_msi           /subscriptions/uami
      azure_container              dev
      auto_create_container        true
      time_slice_format            %Y-%m-%d-%H
      path                         "fluentd/%Y/%m/%d/${tag[1]}"
      azure_object_key_format      %{path}/events-%{time_slice}_%{index}.%{file_extension}
      file_extension               log
      <buffer tag,time>
        @type file
        path /fluentd/buffer
        timekey 1m
        timekey_wait 0s
        timekey_use_utc true
        chunk_limit_size 64m
      </buffer>

The output file looks like this.  data1 is from the previous chunk and data2 is the latest chunk to be appended. Line break is missing between data1 and data2

> {"event": "data1"}
{"event": "data1"}
{"event": "data1"}{"event": "data2"}
{"event": "data2"}
{"event": "data2"}

**Comment by oleewere** [comment]
@shibug , probably it's fixed by https://github.com/oleewere/fluent-plugin-azurestorage-gen2/commit/e836cf6d34f0b1e606d422bcc6644cd163bea61c , i will consider to add config about manipulating  the line splitters, could be useful

**Comment by shibug** [comment]
@oleewere I just tested with the new release (v0.1.5) and this issue still persists.  I will look into the code later tonight or tomorrow.

Thanks for all the help.  I am using your plugin in my project...:)

**Comment by shibug** [comment]
Actually this release is failing to write chunks to ADLS with the below error:

> 2020-01-03 03:33:01 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `each' for #<Fluent::Plugin::Buffer::FileChunk:0x000055d27c098518>"
  2020-01-03 03:33:01 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-azurestorage-gen2-0.1.5/lib/fluent/plugin/out_azurestorage_gen2.rb:132:in `write'
  2020-01-03 03:33:01 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-01-03 03:33:01 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-01-03 03:33:01 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-01-03 03:33:01 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-01-03 03:33:01 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_2ae93df10724/59b33f6dbdc9210ed9a8ba11dca3f7d7.log

We have reverted back to prior release (v0.1.4)

**Comment by oleewere** [comment]
is it right if i will testing your inputs exactly as you provided? (so that's all the fields in the input as a json) I'm not absolutely sure is that related with the changes, until that im reopening this issue

**Comment by oleewere** [comment]
seems like last char is missing after append a file on azure side, (but the body content of the request looks fine), also it adds an empty content-type to the txt files, if that's the case with gzipped contents as well, that would explain why compressed files are corrupt on download (https://github.com/oleewere/fluent-plugin-azurestorage-gen2/issues/3)

**Comment by oleewere** [comment]
@shibug , the issue that you have faced with 0.1.5, you can workaround by using `store_as` with value`text` in the output configuration as iterating on chunk does not happen if text compression is used. this is because of custom formats.
im trying to implement to support both custom formats + handle chunks in memory without writing it to a file

**Comment by shibug** [comment]
I am using fluent-plugin-kafka as an input plugin to consume messages from a topic which contains JSON messages.  By default the message format of that plugin is JSON.
I then use a record transformer plugin to add a few fields including the time of the event.
I then pass it to this plugin.  Let me try the new version 0.1.6

**Comment by shibug** [comment]
This issue has been resolved, please close.
